# # IN this file we will use gpt to interact with the sympy and attempt tot mark the students work
from openai import OpenAI
from dotenv import load_dotenv
import os 

# Load environment variables from .env file

load_dotenv

client = OpenAI(
    organization =os.getenv("OPENAI_ORG_ID"),
    api_key = os.getenv("OPENAI_API_KEY")
)

def grade_feedback(feedBackData: dict[str, str]):
    
    print(f'the question data for the llm  is {feedBackData}')
    completion = client.chat.completions.create(
    model="chatgpt-4o-latest",
    messages=[{
        "role": "developer", 
         "content": feedBackData["questionData"]["gpt-role-content"]
    },{
        "role": "user", 
        "content": f"Here is the students work to provide feedack on it is given in sympy {feedBackData['usersSympyResponse']}"
        
    },],
    temperature=0.7,
    max_tokens=2000,
    store= True,
) 
    feedback = completion.choices[0].message.content
    print(f'The feedback generated by gpt is {feedback}')
    return feedback


    




